"""Add dissolve_reason and dissolve_time fields to Team model

Revision ID: 5b540e82311e
Revises: 
Create Date: 2026-04-28 15:30:32.182873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b540e82311e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dissolve_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('dissolve_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('dissolve_time')
        batch_op.drop_column('dissolve_reason')

    # ### end Alembic commands ###
